include(FetchContent)
function(ramag_configure_pinned_dependencies)
  if(RAMAG_SUFKIT_SOURCE_DIR)
    ramag_require_clean_commit("${RAMAG_SUFKIT_SOURCE_DIR}" "${RAMAG_SUFKIT_COMMIT}" "sufkit")
    set(FETCHCONTENT_SOURCE_DIR_SUFKIT "${RAMAG_SUFKIT_SOURCE_DIR}")
  endif()
  set(SUFKIT_ENABLE_SEQPRO OFF CACHE BOOL "" FORCE)
  set(SUFKIT_BUILD_TESTS OFF CACHE BOOL "" FORCE)
  set(SUFKIT_BUILD_BENCHMARKS OFF CACHE BOOL "" FORCE)
  set(_ramag_parent_build_testing "${BUILD_TESTING}")
  set(BUILD_TESTING OFF CACHE BOOL "Build project tests" FORCE)
  FetchContent_Declare(sufkit
    GIT_REPOSITORY https://github.com/malabz/sufkit.git
    GIT_TAG "${RAMAG_SUFKIT_COMMIT}" GIT_SHALLOW FALSE GIT_PROGRESS TRUE)
  FetchContent_MakeAvailable(sufkit)
  set(BUILD_TESTING "${_ramag_parent_build_testing}" CACHE BOOL "Build project tests" FORCE)
  FetchContent_GetProperties(sufkit SOURCE_DIR _ramag_sufkit_source_dir)
  ramag_require_clean_commit("${_ramag_sufkit_source_dir}" "${RAMAG_SUFKIT_COMMIT}" "resolved sufkit")
  if(NOT TARGET sufkit::sufkit)
    message(FATAL_ERROR "Pinned sufkit did not define sufkit::sufkit")
  endif()
endfunction()
